name: Test
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@main
      - name: node-version
        uses: actions/setup-node@main
        with:
          node-version: '12'
      - name: npm-install
        run: npm install
      - name: unit-test
        run: npm test
